/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830U)
#define RCC_APB2ENR (*(volatile uint32_t *)0x40023844U)

#define GPIOA_MODER (*(volatile uint32_t *)0x40020000U)
#define GPIOA_BSRR  (*(volatile uint32_t *)0x40020018U)
#define GPIOA_AFRL  (*(volatile uint32_t *)0x40020020U)

#define SPI1_CR1    (*(volatile uint32_t *)0x40013000U)
#define SPI1_SR     (*(volatile uint32_t *)0x40013008U)
#define SPI1_DR     (*(volatile uint8_t *)0x4001300CU)

static inline void cs_high(void){
	GPIOA_BSRR = (1U << 4U);
}

static inline void cs_low(void){
	GPIOA_BSRR = (1U << (4U + 16U));
}

static void spi1_init(void){
	RCC_AHB1ENR |= (1U << 0U);
	RCC_APB2ENR |= (1U << 12U);

	// PA4 = GPIO Output for CS
	GPIOA_MODER &= ~(3U << (4U * 2U));
	GPIOA_MODER |=  (1U << (4U * 2U));

	cs_high();

	// PA5 = Alternate Function for SPI1_SCK
	GPIOA_MODER &= ~(3U << (5U * 2U));
	GPIOA_MODER |=  (2U << (5U * 2U));

	// PA6 = Alternate Function for SPI1_MISO
	GPIOA_MODER &= ~(3U << (6U * 2U));
	GPIOA_MODER |=  (2U << (6U * 2U));

	// PA7 = Alternate Function for SPI1_MOSI
	GPIOA_MODER &= ~(3U << (7U * 2U));
	GPIOA_MODER |=  (2U << (7U * 2U));

	GPIOA_AFRL &= ~(0xFU << (5U * 4U));
	GPIOA_AFRL |=  (5U   << (5U * 4U));

	GPIOA_AFRL &= ~(0xFU << (6U * 4U));
	GPIOA_AFRL |=  (5U   << (6U * 4U));

	GPIOA_AFRL &= ~(0xFU << (7U * 4U));
	GPIOA_AFRL |=  (5U   << (7U * 4U));

	// SPI1 Master mode
	SPI1_CR1 |= (1U << 2U);

	// SPI Mode 0: CPOL = 0, CPHA = 0
	SPI1_CR1 &= ~((1U << 1U) | (1U << 0U));

	// Baud rate = PCLK / 8
	SPI1_CR1 &= ~(7U << 3U);
	SPI1_CR1 |=  (2U << 3U);

	// MSB First
	SPI1_CR1 &= ~(1U << 7U);

	// Software NSS management
	SPI1_CR1 |= (1U << 9U);   // SSM = 1
	SPI1_CR1 |= (1U << 8U);   // SSI = 1

	// 8-bit data frame
	SPI1_CR1 &= ~(1U << 11U); // DFF = 0

	// Enable SPI1 last
	SPI1_CR1 |= (1U << 6U);   // SPE = 1
}

static uint8_t spi1_transfer(uint8_t data){
	while(!(SPI1_SR & (1U << 1U))){

	}

	SPI1_DR = data;

	while(!(SPI1_SR & (1U << 0U))){

	}

	return SPI1_DR;
}

int main(void)
{
	volatile uint8_t tx_data = 0x3CU;
	volatile uint8_t rx_data = 0U;

	spi1_init();

	cs_low();

	rx_data = spi1_transfer(tx_data);

	while(SPI1_SR & (1U << 7U)){

	}

	cs_high();

    /* Loop forever */
	for(;;){

	}
}
