/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define LED_PIN 5U

#define RCC_AHB1ENR (*(volatile uint32_t*)0x40023830U)
#define RCC_APB1ENR (*(volatile uint32_t*)0x40023840U)

#define GPIOA_MODER (*(volatile uint32_t*)0x40020000U)
#define GPIOA_BSRR  (*(volatile uint32_t*)0x40020018U)

#define TIM2_CR1    (*(volatile uint32_t*)0x40000000U)
#define TIM2_DIER   (*(volatile uint32_t*)0x4000000CU)
#define TIM2_SR     (*(volatile uint32_t*)0x40000010U)
#define TIM2_EGR    (*(volatile uint32_t*)0x40000014U)
#define TIM2_PSC    (*(volatile uint32_t*)0x40000028U)
#define TIM2_ARR    (*(volatile uint32_t*)0x4000002CU)

#define NVIC_ISER0  (*(volatile uint32_t*)0xE000E100U)

static void gpio_init(void)
{
    RCC_AHB1ENR |= (1U << 0U);

    GPIOA_MODER &= ~(3U << (LED_PIN * 2U));
    GPIOA_MODER |=  (1U << (LED_PIN * 2U));

    GPIOA_BSRR = (1U << (LED_PIN + 16U));
}

static void tim2_init(void)
{
    RCC_APB1ENR |= (1U << 0U);

    TIM2_PSC = 15999U;
    TIM2_ARR = 999U;

    TIM2_EGR |= (1U << 0U);
    TIM2_SR &= ~(1U << 0U);

    TIM2_DIER |= (1U << 0U);
    NVIC_ISER0 |= (1U << 28U);

    TIM2_CR1 |= (1U << 0U);
}

void TIM2_IRQHandler(void)
{
    static uint8_t led_state = 0U;

    if ((TIM2_SR & (1U << 0U)) != 0U)
    {
        TIM2_SR &= ~(1U << 0U);

        if (led_state == 0U)
        {
            GPIOA_BSRR = (1U << LED_PIN);
            led_state = 1U;
        }
        else
        {
            GPIOA_BSRR = (1U << (LED_PIN + 16U));
            led_state = 0U;
        }
    }
}

int main(void)
{

	 gpio_init();
	 tim2_init();

    /* Loop forever */
	for(;;);
}
