/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR *((volatile uint32_t*)0x40023830U)

#define GPIOA_MODER *((volatile uint32_t*)0x40020000U)
#define GPIOA_BSRR *((volatile uint32_t*)0x40020018U)

#define GPIOC_MODER *((volatile uint32_t*)0x40020800U)
#define GPIOC_IDR *((volatile uint32_t*)0x40020810U)

#define LED_PIN 5U
#define BUTTON_PIN 13U

#define GPIOA_EN_BIT 0U
#define GPIOC_EN_BIT 2U

#define BUTTON_STATE_PRESS 0U
#define DEBOUNCE_DELAY_COUNT 50000U

static void gpio_init(void){
	RCC_AHB1ENR |= ((1U << GPIOA_EN_BIT) | (1U << GPIOC_EN_BIT));
	GPIOA_MODER &= ~(3U << (LED_PIN * 2U));
	GPIOA_MODER |= (1U << (LED_PIN * 2U));
	GPIOC_MODER &= ~((3U << (BUTTON_PIN * 2U)));
}

static inline void led_on(void){
	GPIOA_BSRR = (1U << LED_PIN);
}
static inline void led_off(void){
	GPIOA_BSRR = (1U << (LED_PIN + 16U));
}

static uint32_t button_read(void){
	return (GPIOC_IDR & (1U << BUTTON_PIN));
}

static bool button_is_pressed(void){
	return(button_read() == BUTTON_STATE_PRESS);
}

static void delay(uint32_t delay_count){
	for(volatile uint32_t i = 0 ; i < delay_count ; i++){

	}
}

int main(void)
{
	gpio_init();

	bool previous_button = false;
	bool current_button = false;
	bool led_state = false;

    /* Loop forever */
	for(;;){

		current_button = button_is_pressed();

		if(current_button != previous_button){

			delay(DEBOUNCE_DELAY_COUNT);

			current_button = button_is_pressed();

			if(current_button != previous_button){

				previous_button = current_button;

				if(current_button){
					led_state = !led_state;
				}
			}
		}


		if(led_state){
			led_on();
		}
		else{
			led_off();
		}

	}
}
