/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR (*(volatile uint32_t*)0x40023830)
#define RCC_APB1ENR (*(volatile uint32_t*)0x40023840)

#define GPIOA_MODER (*(volatile uint32_t*)0x40020000)
#define GPIOA_AFRL	(*(volatile uint32_t*)0x40020020)
#define GPIOA_BSRR 	(*(volatile uint32_t*)0x40020018)

#define USART2_SR 	(*(volatile uint32_t*)0x40004400)
#define USART2_DR	(*(volatile uint32_t*)0x40004404)
#define USART2_BRR	(*(volatile uint32_t*)0x40004408)
#define USART2_CR1	(*(volatile uint32_t*)0x4000440C)
#define USART2_CR2	(*(volatile uint32_t*)0x40004410)

#define NVIC_ISER1	(*(volatile uint32_t*)0xE000E104)

#define PA2_PIN 2U
#define PA3_PIN 3U
#define LED_PIN 5U

#define UART_RX_BUFFER_SIZE 8U
#define CMD_BUFFER_SIZE 32U

static volatile char uart_rx_buffer[UART_RX_BUFFER_SIZE];
static volatile uint8_t uart_rx_head;
static volatile uint8_t uart_rx_tail;
static volatile uint32_t uart_rx_overflow_count;

static char cmd_buffer[CMD_BUFFER_SIZE];
static uint8_t cmd_index;
static uint8_t cmd_overflow;

static void uart2_write_char(char ch){
	while((USART2_SR & (1U << 7U)) == 0U){

	}

	USART2_DR = ch;
}

static void uart2_write_string(const char *str){
	while(*str != '\0'){
		uart2_write_char(*str);
		str++;
	}
}

static void uart_rx_push(char ch){
	uint8_t next_head = (uart_rx_head + 1U) % UART_RX_BUFFER_SIZE;

	if(next_head != uart_rx_tail){
		uart_rx_buffer[uart_rx_head] = ch;
		uart_rx_head = next_head;
	}
	else{
		uart_rx_overflow_count++;
	}
}

static uint8_t uart_rx_pop(char* ch){
	if(uart_rx_tail != uart_rx_head){
		*ch = uart_rx_buffer[uart_rx_tail];
		uart_rx_tail = (uart_rx_tail + 1U) % UART_RX_BUFFER_SIZE;

		return 1U;
	}
	else{
		return 0U;
	}
}

static uint8_t string_equal(const char*a , const char*b){
	for(;;){
		if(*a == *b){
			if(*a == '\0'){
				return 1U;
			}
			a++;
			b++;
		}
		else{
			return 0U;
		}
	}
}

static void process_cmd(const char* cmd){
	if(string_equal(cmd , "LED ON") == 1U){
		GPIOA_BSRR = (1U << LED_PIN);
	}
	else if(string_equal(cmd , "LED OFF") == 1U){
		GPIOA_BSRR = (1U << (LED_PIN + 16U));
	}
	else if(string_equal(cmd , "STATUS") == 1U){
		uart2_write_string("STATUS OK\r\n");
	}
	else{
		uart2_write_string("ERROR\r\n");
	}
}


void USART2_IRQHandler(void){
	if((USART2_SR & (1U << 5U)) != 0U){
		uart_rx_push((char)USART2_DR);
	}
}

int main(void)
{
	RCC_AHB1ENR |= (1U << 0U);
	RCC_APB1ENR |= (1U << 17U);

	GPIOA_MODER &= ~(3U << (PA2_PIN * 2U));
	GPIOA_MODER |= 	(2U << (PA2_PIN * 2U));
	GPIOA_MODER &= ~(3U << (PA3_PIN * 2U));
	GPIOA_MODER |= 	(2U << (PA3_PIN * 2U));
	GPIOA_MODER &= ~(3U << (LED_PIN * 2U));
	GPIOA_MODER |= 	(1U << (LED_PIN * 2U));

	GPIOA_AFRL  &= ~(15U << (PA2_PIN * 4U));
	GPIOA_AFRL	|= 	(7U << (PA2_PIN *4U));
	GPIOA_AFRL  &= ~(15U << (PA3_PIN * 4U));
	GPIOA_AFRL	|= 	(7U << (PA3_PIN *4U));

	USART2_CR1	&= ~((1U << 15U) | (1U << 12U) | (1U << 10U));
	USART2_CR2	&= ~(3U << 12U);
	USART2_BRR	= 0x683U;
	USART2_CR1	|= (1U << 3U);
	USART2_CR1	|= (1U << 2U);
	USART2_CR1	|= (1U << 13U);
	USART2_CR1 	|= (1U << 5U);

	NVIC_ISER1	|= (1U << 6U);

    /* Loop forever */
	for(;;){

		char ch;

		if(uart_rx_pop(&ch) != 0U){

			if(ch == '\r'){
				if(cmd_overflow == 0U){
					cmd_buffer[cmd_index] = '\0';
					process_cmd(cmd_buffer);
				}
				cmd_index = 0U;
				cmd_overflow = 0U;
			}
			else if(ch == '\n'){

			}
			else{
				if(cmd_overflow == 0U){
					if(cmd_index < (CMD_BUFFER_SIZE - 1U)){
							cmd_buffer[cmd_index] = ch;
							cmd_index ++;
					}
					else{
						cmd_overflow = 1U;
					}
				}
			}
		}
	}
}
