/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR 	(*(volatile uint32_t*)0x40023830U)

#define GPIOA_MODER 	(*(volatile uint32_t*)0x40020000U)
#define GPIOA_BSRR 		(*(volatile uint32_t*)0x40020018U)

#define GPIOC_MODER 	(*(volatile uint32_t*)0x40020800U)
#define GPIOC_IDR 		(*(volatile uint32_t*)0x40020810U)

#define RCC_APB2ENR     (*(volatile uint32_t *)0x40023844U)

#define SYSCFG_EXTICR4  (*(volatile uint32_t *)0x40013814U)

#define EXTI_IMR        (*(volatile uint32_t *)0x40013C00U)
#define EXTI_FTSR       (*(volatile uint32_t *)0x40013C0CU)
#define EXTI_PR         (*(volatile uint32_t *)0x40013C14U)

#define NVIC_ISER1      (*(volatile uint32_t *)0xE000E104U)

#define GPIOA_EN_BIT 0U
#define GPIOC_EN_BIT 2U

#define LED_PIN 5U
#define BUTTON_PIN 13U

static void exti_init(void){
	RCC_APB2ENR |= (1U << 14U);

	SYSCFG_EXTICR4 &= ~(15U << 4U);
	SYSCFG_EXTICR4 |= (2U << 4U);

	EXTI_IMR |= (1U << BUTTON_PIN);
	EXTI_FTSR |= (1U << BUTTON_PIN);

	NVIC_ISER1 = (1U << 8U);
}

static void gpio_init(void){
	RCC_AHB1ENR |= ((1U << GPIOA_EN_BIT) | (1U << GPIOC_EN_BIT));

	GPIOA_MODER &= ~(3U << (LED_PIN * 2U));
	GPIOA_MODER |= (1U << LED_PIN * 2U);
	GPIOC_MODER &= ~(3U << (BUTTON_PIN * 2U));
}

static inline void led_on(void){
	GPIOA_BSRR = (1U << LED_PIN);
}
static inline void led_off(void){
	GPIOA_BSRR = (1U << (LED_PIN + 16U));
}

static inline void cpu_wait_for_interrupt(void){
	__asm volatile ("wfi");
}

static volatile bool button_event = false;

void EXTI15_10_IRQHandler(void){
	if(EXTI_PR & (1U << BUTTON_PIN)){
		EXTI_PR = (1U << BUTTON_PIN);
		button_event = true;
	}
}

int main(void)
{
	bool led_state = false;

	gpio_init();
	exti_init();

	led_off();

    /* Loop forever */
	for(;;){
		if(button_event){
			button_event = false;
			led_state = !led_state;

			if(led_state){
				led_on();
			}
			else{
				led_off();
			}
		}

		cpu_wait_for_interrupt();
	}
}
