/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1NER *((volatile uint32_t*)0x40023830U)
#define GPIOA_MODER *((volatile uint32_t*)0x40020000U)
#define GPIOA_ODR *((volatile uint32_t*)0x40020014U)
#define GPIOA_BSRR *((volatile uint32_t*)0x40020018U)

#define LED_PIN 5U
#define GPIOA_EN_BIT 0U
#define BLINK_DELAY_COUNT 500000U

static void gpio_init(void){
	RCC_AHB1NER |= (1U << GPIOA_EN_BIT);

	GPIOA_MODER &= ~(3U << (LED_PIN * 2U));
	GPIOA_MODER |= (1U << (LED_PIN * 2U));
}

static inline void led_on(void){
	GPIOA_BSRR = (1U << LED_PIN);
}
static inline void led_off(void){
	GPIOA_BSRR = (1U << (LED_PIN + 16));
}

static void delay(uint32_t delay_count){
	for(volatile uint32_t i = 0 ; i < delay_count ; i++){}
}

int main(void)
{
	gpio_init();

    /* Loop forever */
	for(;;){

		led_on();

		delay(BLINK_DELAY_COUNT);

		led_off();

		delay(BLINK_DELAY_COUNT);

	}
}
