/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_AHB1ENR (*(volatile uint32_t*)0x40023830U)
#define RCC_APB1ENR (*(volatile uint32_t*)0x40023840U)

#define GPIOA_MODER (*(volatile uint32_t*)0x40020000U)
#define GPIOA_AFRL  (*(volatile uint32_t*)0x40020020U)

#define PA5_PIN 5U

#define TIM2_PSC 	(*(volatile uint32_t*)0x40000028U)
#define TIM2_ARR 	(*(volatile uint32_t*)0x4000002CU)
#define TIM2_CCR1 	(*(volatile uint32_t*)0x40000034U)
#define TIM2_CCMR1	(*(volatile uint32_t*)0x40000018U)
#define TIM2_CCER	(*(volatile uint32_t*)0x40000020U)
#define TIM2_CR1	(*(volatile uint32_t*)0x40000000U)
#define TIM2_EGR	(*(volatile uint32_t*)0x40000014U)

static void gpio_init(void){
	RCC_AHB1ENR |= (1U << 0U);

	GPIOA_MODER &= ~(3U << (PA5_PIN*2U));
	GPIOA_MODER |= 	(2U << (PA5_PIN*2U));

	GPIOA_AFRL 	&= ~(15U << (PA5_PIN*4U));
	GPIOA_AFRL 	|=  (1U << (PA5_PIN*4U));
}

static void tim2_pwm_init(void){
	RCC_APB1ENR |= (1U << 0U);

	TIM2_PSC = 15U;
	TIM2_ARR = 999U;
	TIM2_CCR1 = 500U;

	TIM2_CCMR1 	&= ~(7U << 4U);
	TIM2_CCMR1 	|= (6U << 4U);
	TIM2_CCMR1 	|= (1U << 3U);

	TIM2_CCER  	|= (1U << 0U);
	TIM2_CR1	|= (1U << 7U);
	TIM2_EGR	 = (1U << 0U);
	TIM2_CR1	|= (1U << 0U);

}

int main(void)
{
	gpio_init();
	tim2_pwm_init();
    /* Loop forever */
	for(;;){

	}
}
